sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: stc0HeJH5mBC3wduJUZrQUZdNbSuajTNZNB6QmcMXP0UA+9pcOO4zXiWL+ziEL3yxpnQb+Vcgx4qhG1s6/KYWk3pCdMU+VdyHml93jbQHHozPekv39z6+kHJWZtK8/TLwBhgc0kuLWzECmhMz9H7F9lIaUFPLLxliL6GN/poFOtWXhFFwbWzHs3Ww6yhBR05fSc4nI0fiUlBubuXwBLYLEGTiVBTMdR/hzZ+74Z3yadS/3JKHoU/zqjhMUnxpeaH9cHnkJPO4lsG9wcsxF4lJO5U/PrkeyNqP/zB6RlIUmHOCh4X+Hqa9Svw7cVNbxDToZ7AkMzYrFUnflXdF11XDioPdfTW6Cjj3q+SLzCZ1NLieIgo+N238jc7Uil73vCiLZ4obeBP7Bgh57ME1gZS7oS//ilLLa+NuCCCts1g1+gcXs2nuGGSnBOwGSF9tMBmOHIEdhVaTZ2pfeTpplQntU0tTRegqWbbZlTY2VmSAfDVXW9Me5BYVFY+Xjn05m8GjNbLvHl7TG/xcI/Y4HDRfxZb2kBzmLpBnd59fxLQQ9D8F6taAF//JezD8jcLI4AWsIHpBqsczXcqVoo5HazeQBDzW+IDzbJ5kfU/1LL2owX2z1VxGhxM4EKS5WIqtd3hx9fp9bYBqpgl/nXVrKLyDhYxo3VtF1D1dCiek7SL8sc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Borough_5210
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy